// <auto-generated />
using System;
using CUTDataScienceClub.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CUTDataScienceClub.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251012170631_creatingProjectsTableAndSeeding")]
    partial class creatingProjectsTableAndSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CUTDataScienceClub.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Organizer")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A beginner-friendly intro to data science concepts.",
                            EndDate = new DateTime(2025, 11, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            Location = "Room A1",
                            Organizer = "DSC",
                            StartDate = new DateTime(2025, 11, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Intro to Data Science"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Hands-on session on using Python for data analysis.",
                            EndDate = new DateTime(2025, 11, 8, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            Location = "Lab 2",
                            Organizer = "DSC",
                            StartDate = new DateTime(2025, 11, 8, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Python for Analysis"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Probability and statistics refresher.",
                            EndDate = new DateTime(2025, 11, 15, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            Location = "Room B3",
                            Organizer = "Math Dept",
                            StartDate = new DateTime(2025, 11, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Statistics Workshop"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Overview of supervised and unsupervised learning.",
                            EndDate = new DateTime(2025, 11, 22, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            Location = "Auditorium",
                            Organizer = "DSC",
                            StartDate = new DateTime(2025, 11, 22, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Machine Learning 101"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Create compelling visuals with Tableau.",
                            EndDate = new DateTime(2025, 12, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            Location = "Lab 1",
                            Organizer = "DSC",
                            StartDate = new DateTime(2025, 12, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Data Viz with Tableau"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Intro to R and tidyverse.",
                            EndDate = new DateTime(2025, 12, 6, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            Location = "Room C2",
                            Organizer = "Stats Club",
                            StartDate = new DateTime(2025, 12, 6, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "R for Data Science"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Talk on scalable data systems.",
                            EndDate = new DateTime(2025, 12, 12, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            Location = "Conference Hall",
                            Organizer = "CS Dept",
                            StartDate = new DateTime(2025, 12, 12, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "Big Data Architectures"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Natural Language Processing primer.",
                            EndDate = new DateTime(2026, 1, 10, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            Location = "Room D1",
                            Organizer = "AI Group",
                            StartDate = new DateTime(2026, 1, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "NLP Basics"
                        },
                        new
                        {
                            Id = 9,
                            Description = "How to approach Kaggle problems.",
                            EndDate = new DateTime(2026, 1, 17, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            Location = "Lab 3",
                            Organizer = "DSC",
                            StartDate = new DateTime(2026, 1, 17, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Kaggle Competition Prep"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Panel on ethical considerations in AI.",
                            EndDate = new DateTime(2026, 1, 24, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            Location = "Auditorium",
                            Organizer = "Philosophy Dept",
                            StartDate = new DateTime(2026, 1, 24, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Ethics in AI"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Two-day bootcamp on ETL and pipelines.",
                            EndDate = new DateTime(2026, 2, 6, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            Location = "Workshop Room",
                            Organizer = "DSC",
                            StartDate = new DateTime(2026, 2, 5, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Data Engineering Bootcamp"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Analyzing temporal data with ARIMA and more.",
                            EndDate = new DateTime(2026, 2, 14, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            Location = "Room B2",
                            Organizer = "Stats Club",
                            StartDate = new DateTime(2026, 2, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Time Series Analysis"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Techniques for communicating results.",
                            EndDate = new DateTime(2026, 2, 21, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            Location = "Room A2",
                            Organizer = "Communications",
                            StartDate = new DateTime(2026, 2, 21, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Data Storytelling"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Intro to deep neural networks.",
                            EndDate = new DateTime(2026, 3, 3, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            Location = "Lab 4",
                            Organizer = "AI Group",
                            StartDate = new DateTime(2026, 3, 3, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Deep Learning Workshop"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Meet industry recruiters and alumni.",
                            EndDate = new DateTime(2026, 3, 12, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            Location = "Conference Hall",
                            Organizer = "DSC",
                            StartDate = new DateTime(2026, 3, 12, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Career Night"
                        });
                });

            modelBuilder.Entity("CUTDataScienceClub.Models.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CurrentLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Program")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentLevel = "100",
                            FullName = "Alice Johnson",
                            Program = "Data Science",
                            RegNumber = "DSC001"
                        },
                        new
                        {
                            Id = 2,
                            CurrentLevel = "200",
                            FullName = "Bob Smith",
                            Program = "Data Science",
                            RegNumber = "DSC002"
                        },
                        new
                        {
                            Id = 3,
                            CurrentLevel = "300",
                            FullName = "Carol Lee",
                            Program = "Statistics",
                            RegNumber = "DSC003"
                        },
                        new
                        {
                            Id = 4,
                            CurrentLevel = "400",
                            FullName = "David Kim",
                            Program = "Computer Science",
                            RegNumber = "DSC004"
                        },
                        new
                        {
                            Id = 5,
                            CurrentLevel = "200",
                            FullName = "Eva Brown",
                            Program = "Data Science",
                            RegNumber = "DSC005"
                        },
                        new
                        {
                            Id = 6,
                            CurrentLevel = "100",
                            FullName = "Frank White",
                            Program = "Mathematics",
                            RegNumber = "DSC006"
                        },
                        new
                        {
                            Id = 7,
                            CurrentLevel = "300",
                            FullName = "Grace Green",
                            Program = "Data Science",
                            RegNumber = "DSC007"
                        },
                        new
                        {
                            Id = 8,
                            CurrentLevel = "400",
                            FullName = "Henry Black",
                            Program = "Statistics",
                            RegNumber = "DSC008"
                        },
                        new
                        {
                            Id = 9,
                            CurrentLevel = "200",
                            FullName = "Ivy Blue",
                            Program = "Computer Science",
                            RegNumber = "DSC009"
                        },
                        new
                        {
                            Id = 10,
                            CurrentLevel = "100",
                            FullName = "Jack Red",
                            Program = "Mathematics",
                            RegNumber = "DSC010"
                        });
                });

            modelBuilder.Entity("CUTDataScienceClub.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Owner")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RepositoryUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Technologies")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A web portal for students to access resources and events.",
                            EndDate = new DateTime(2025, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Owner = "DSC",
                            RepositoryUrl = "https://github.com/cut-dsc/student-portal",
                            StartDate = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Technologies = "ASP.NET Core, EF Core, Bootstrap",
                            Title = "Student Portal"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Scripts and notebooks for common Kaggle tasks.",
                            IsActive = true,
                            Owner = "Data Team",
                            RepositoryUrl = "https://github.com/cut-dsc/kaggle-prep",
                            StartDate = new DateTime(2024, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Technologies = "Python, Pandas, scikit-learn",
                            Title = "Kaggle Prep Toolkit"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Platform to match students with alumni mentors.",
                            IsActive = true,
                            Owner = "Alumni Affairs",
                            RepositoryUrl = "https://github.com/cut-dsc/alumni-mentorship",
                            StartDate = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Technologies = "Node.js, Express, React",
                            Title = "Alumni Mentorship"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Tool to schedule and manage club events.",
                            EndDate = new DateTime(2025, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Owner = "Events Committee",
                            RepositoryUrl = "https://github.com/cut-dsc/event-scheduler",
                            StartDate = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Technologies = "ASP.NET Core, FullCalendar",
                            Title = "Event Scheduler"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Collection of data visualizations built by members.",
                            IsActive = true,
                            Owner = "Design Team",
                            RepositoryUrl = "https://github.com/cut-dsc/dataviz-gallery",
                            StartDate = new DateTime(2024, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Technologies = "D3.js, JavaScript",
                            Title = "DataViz Gallery"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Shared repository for research projects and papers.",
                            IsActive = true,
                            Owner = "Research Group",
                            RepositoryUrl = "https://github.com/cut-dsc/research-repo",
                            StartDate = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Technologies = "Markdown, LaTeX, Jupyter",
                            Title = "Research Repo"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Aggregates internship and job postings.",
                            IsActive = true,
                            Owner = "Careers",
                            RepositoryUrl = "https://github.com/cut-dsc/job-board",
                            StartDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Technologies = "Python, Scrapy, Elasticsearch",
                            Title = "Job Board Aggregator"
                        },
                        new
                        {
                            Id = 8,
                            Description = "ML model to recommend mentors to mentees.",
                            IsActive = true,
                            Owner = "AI Lab",
                            RepositoryUrl = "https://github.com/cut-dsc/mentor-ai",
                            StartDate = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Technologies = "Python, TensorFlow, scikit-learn",
                            Title = "Mentor Matching AI"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Tool to help members create portfolios.",
                            IsActive = true,
                            Owner = "Career Services",
                            RepositoryUrl = "https://github.com/cut-dsc/portfolio-builder",
                            StartDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Technologies = "React, Node.js",
                            Title = "Portfolio Builder"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Curated datasets with metadata for projects.",
                            IsActive = true,
                            Owner = "Data Team",
                            RepositoryUrl = "https://github.com/cut-dsc/dataset-catalog",
                            StartDate = new DateTime(2024, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Technologies = "Postgres, Python",
                            Title = "Dataset Catalog"
                        },
                        new
                        {
                            Id = 11,
                            Description = "An educational chatbot for tutorials and FAQs.",
                            IsActive = true,
                            Owner = "Education",
                            RepositoryUrl = "https://github.com/cut-dsc/chatbot-tutor",
                            StartDate = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Technologies = "Python, Rasa",
                            Title = "Chatbot Tutor"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Boilerplate code and templates for hackathons.",
                            IsActive = true,
                            Owner = "Hackathon Team",
                            RepositoryUrl = "https://github.com/cut-dsc/hackathon-toolkit",
                            StartDate = new DateTime(2024, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Technologies = "Multiple",
                            Title = "Hackathon Toolkit"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Dashboard for club KPIs and metrics.",
                            IsActive = true,
                            Owner = "Leadership",
                            RepositoryUrl = "https://github.com/cut-dsc/analytics-dashboard",
                            StartDate = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Technologies = "Power BI, SQL, ASP.NET Core",
                            Title = "Analytics Dashboard"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Helps members find study groups by subject.",
                            IsActive = true,
                            Owner = "Community",
                            RepositoryUrl = "https://github.com/cut-dsc/study-groups",
                            StartDate = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Technologies = "React, Firebase",
                            Title = "Study Group Finder"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Mobile companion app for club events and news.",
                            IsActive = true,
                            Owner = "Mobile Team",
                            RepositoryUrl = "https://github.com/cut-dsc/mobile-app",
                            StartDate = new DateTime(2025, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Technologies = "Flutter",
                            Title = "Mobile App"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Track volunteer hours and roles.",
                            IsActive = true,
                            Owner = "Outreach",
                            RepositoryUrl = "https://github.com/cut-dsc/volunteer-tracker",
                            StartDate = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Technologies = "ASP.NET Core, EF Core",
                            Title = "Volunteer Tracker"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Manage sponsor information and proposals.",
                            IsActive = true,
                            Owner = "Sponsorship",
                            RepositoryUrl = "https://github.com/cut-dsc/sponsorship-portal",
                            StartDate = new DateTime(2024, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Technologies = "ASP.NET Core",
                            Title = "Sponsorship Portal"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Series of writeups on club research projects.",
                            IsActive = true,
                            Owner = "Research Group",
                            RepositoryUrl = "https://github.com/cut-dsc/paper-series",
                            StartDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Technologies = "Markdown, LaTeX",
                            Title = "Research Paper Series"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Improve accessibility across club web properties.",
                            IsActive = true,
                            Owner = "Design Team",
                            RepositoryUrl = "https://github.com/cut-dsc/accessibility-audit",
                            StartDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Technologies = "HTML, CSS, JS",
                            Title = "Accessibility Audit"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Migrate older projects into the new monorepo.",
                            EndDate = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Owner = "Platform Team",
                            RepositoryUrl = "https://github.com/cut-dsc/legacy-migration",
                            StartDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Technologies = "Bash, Git",
                            Title = "Legacy Migration"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
