// <auto-generated />
using CUTDataScienceClub.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CUTDataScienceClub.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251012013348_seedingDb")]
    partial class seedingDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CUTDataScienceClub.Models.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CurrentLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Program")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentLevel = "100",
                            FullName = "Alice Johnson",
                            Program = "Data Science",
                            RegNumber = "DSC001"
                        },
                        new
                        {
                            Id = 2,
                            CurrentLevel = "200",
                            FullName = "Bob Smith",
                            Program = "Data Science",
                            RegNumber = "DSC002"
                        },
                        new
                        {
                            Id = 3,
                            CurrentLevel = "300",
                            FullName = "Carol Lee",
                            Program = "Statistics",
                            RegNumber = "DSC003"
                        },
                        new
                        {
                            Id = 4,
                            CurrentLevel = "400",
                            FullName = "David Kim",
                            Program = "Computer Science",
                            RegNumber = "DSC004"
                        },
                        new
                        {
                            Id = 5,
                            CurrentLevel = "200",
                            FullName = "Eva Brown",
                            Program = "Data Science",
                            RegNumber = "DSC005"
                        },
                        new
                        {
                            Id = 6,
                            CurrentLevel = "100",
                            FullName = "Frank White",
                            Program = "Mathematics",
                            RegNumber = "DSC006"
                        },
                        new
                        {
                            Id = 7,
                            CurrentLevel = "300",
                            FullName = "Grace Green",
                            Program = "Data Science",
                            RegNumber = "DSC007"
                        },
                        new
                        {
                            Id = 8,
                            CurrentLevel = "400",
                            FullName = "Henry Black",
                            Program = "Statistics",
                            RegNumber = "DSC008"
                        },
                        new
                        {
                            Id = 9,
                            CurrentLevel = "200",
                            FullName = "Ivy Blue",
                            Program = "Computer Science",
                            RegNumber = "DSC009"
                        },
                        new
                        {
                            Id = 10,
                            CurrentLevel = "100",
                            FullName = "Jack Red",
                            Program = "Mathematics",
                            RegNumber = "DSC010"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
