// <auto-generated />
using System;
using CUTDataScienceClub.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CUTDataScienceClub.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251012032444_creatingEventsTableAndSeedingTheTable")]
    partial class creatingEventsTableAndSeedingTheTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CUTDataScienceClub.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Organizer")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A beginner-friendly intro to data science concepts.",
                            EndDate = new DateTime(2025, 11, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            Location = "Room A1",
                            Organizer = "DSC",
                            StartDate = new DateTime(2025, 11, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Intro to Data Science"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Hands-on session on using Python for data analysis.",
                            EndDate = new DateTime(2025, 11, 8, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            Location = "Lab 2",
                            Organizer = "DSC",
                            StartDate = new DateTime(2025, 11, 8, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Python for Analysis"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Probability and statistics refresher.",
                            EndDate = new DateTime(2025, 11, 15, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            Location = "Room B3",
                            Organizer = "Math Dept",
                            StartDate = new DateTime(2025, 11, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Statistics Workshop"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Overview of supervised and unsupervised learning.",
                            EndDate = new DateTime(2025, 11, 22, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            Location = "Auditorium",
                            Organizer = "DSC",
                            StartDate = new DateTime(2025, 11, 22, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Machine Learning 101"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Create compelling visuals with Tableau.",
                            EndDate = new DateTime(2025, 12, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            Location = "Lab 1",
                            Organizer = "DSC",
                            StartDate = new DateTime(2025, 12, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Data Viz with Tableau"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Intro to R and tidyverse.",
                            EndDate = new DateTime(2025, 12, 6, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            Location = "Room C2",
                            Organizer = "Stats Club",
                            StartDate = new DateTime(2025, 12, 6, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "R for Data Science"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Talk on scalable data systems.",
                            EndDate = new DateTime(2025, 12, 12, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            Location = "Conference Hall",
                            Organizer = "CS Dept",
                            StartDate = new DateTime(2025, 12, 12, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "Big Data Architectures"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Natural Language Processing primer.",
                            EndDate = new DateTime(2026, 1, 10, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            Location = "Room D1",
                            Organizer = "AI Group",
                            StartDate = new DateTime(2026, 1, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "NLP Basics"
                        },
                        new
                        {
                            Id = 9,
                            Description = "How to approach Kaggle problems.",
                            EndDate = new DateTime(2026, 1, 17, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            Location = "Lab 3",
                            Organizer = "DSC",
                            StartDate = new DateTime(2026, 1, 17, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Kaggle Competition Prep"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Panel on ethical considerations in AI.",
                            EndDate = new DateTime(2026, 1, 24, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            Location = "Auditorium",
                            Organizer = "Philosophy Dept",
                            StartDate = new DateTime(2026, 1, 24, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Ethics in AI"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Two-day bootcamp on ETL and pipelines.",
                            EndDate = new DateTime(2026, 2, 6, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            Location = "Workshop Room",
                            Organizer = "DSC",
                            StartDate = new DateTime(2026, 2, 5, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Data Engineering Bootcamp"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Analyzing temporal data with ARIMA and more.",
                            EndDate = new DateTime(2026, 2, 14, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            Location = "Room B2",
                            Organizer = "Stats Club",
                            StartDate = new DateTime(2026, 2, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Time Series Analysis"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Techniques for communicating results.",
                            EndDate = new DateTime(2026, 2, 21, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            Location = "Room A2",
                            Organizer = "Communications",
                            StartDate = new DateTime(2026, 2, 21, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Data Storytelling"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Intro to deep neural networks.",
                            EndDate = new DateTime(2026, 3, 3, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            Location = "Lab 4",
                            Organizer = "AI Group",
                            StartDate = new DateTime(2026, 3, 3, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Deep Learning Workshop"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Meet industry recruiters and alumni.",
                            EndDate = new DateTime(2026, 3, 12, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            Location = "Conference Hall",
                            Organizer = "DSC",
                            StartDate = new DateTime(2026, 3, 12, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Career Night"
                        });
                });

            modelBuilder.Entity("CUTDataScienceClub.Models.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CurrentLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Program")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentLevel = "100",
                            FullName = "Alice Johnson",
                            Program = "Data Science",
                            RegNumber = "DSC001"
                        },
                        new
                        {
                            Id = 2,
                            CurrentLevel = "200",
                            FullName = "Bob Smith",
                            Program = "Data Science",
                            RegNumber = "DSC002"
                        },
                        new
                        {
                            Id = 3,
                            CurrentLevel = "300",
                            FullName = "Carol Lee",
                            Program = "Statistics",
                            RegNumber = "DSC003"
                        },
                        new
                        {
                            Id = 4,
                            CurrentLevel = "400",
                            FullName = "David Kim",
                            Program = "Computer Science",
                            RegNumber = "DSC004"
                        },
                        new
                        {
                            Id = 5,
                            CurrentLevel = "200",
                            FullName = "Eva Brown",
                            Program = "Data Science",
                            RegNumber = "DSC005"
                        },
                        new
                        {
                            Id = 6,
                            CurrentLevel = "100",
                            FullName = "Frank White",
                            Program = "Mathematics",
                            RegNumber = "DSC006"
                        },
                        new
                        {
                            Id = 7,
                            CurrentLevel = "300",
                            FullName = "Grace Green",
                            Program = "Data Science",
                            RegNumber = "DSC007"
                        },
                        new
                        {
                            Id = 8,
                            CurrentLevel = "400",
                            FullName = "Henry Black",
                            Program = "Statistics",
                            RegNumber = "DSC008"
                        },
                        new
                        {
                            Id = 9,
                            CurrentLevel = "200",
                            FullName = "Ivy Blue",
                            Program = "Computer Science",
                            RegNumber = "DSC009"
                        },
                        new
                        {
                            Id = 10,
                            CurrentLevel = "100",
                            FullName = "Jack Red",
                            Program = "Mathematics",
                            RegNumber = "DSC010"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
